import type { PageDef } from './types'

/**
 * The main track of the talk: 23 pages in run-of-show order for a 90-minute
 * session. Deep-dive sub-tracks (the nine styles, the ten katas) live in their
 * own files and hang off `styles` and `library`.
 */
export const mainPages: PageDef[] = [
  {
    id: 'title',
    path: '/',
    title: 'Welcome',
    section: 'intro',
    track: 'main',
    component: 'title',
    minute: 0,
    hero: {
      kicker: 'JEM-id Dev Cafe 2026 · Randy Vroegop',
      title: 'Architecture is a team sport',
      subtitle: 'Architectural Katas + C4: practising software architecture together',
      bullets: [
        'Why repeated practice beats occasional heroics',
        'The method: katas, C4 rounds, hard but fair feedback',
        'A live round, then a playbook to take home',
      ],
    },
    notes: [
      'Welcome the room and point at the QR code. The deck is a website; everyone can open it on a phone and follow along.',
      'Say the claim in one breath: architecture gets better when a whole team practises it, not when one architect decides alone.',
      'Walk the agenda strip: talk until minute 57, a live kata round until minute 86, then the playbook and questions.',
      'Ask for hands: who has drawn an architecture that shipped? Who did it more than five times? Remember the numbers for the next page.',
      'Ground rules: phones are welcome, laptops close during the live round, questions at any time.',
      'Three minutes here at most. Transition: "Let me start with a question Ted Neward asked back in 2011."',
    ],
  },
  {
    id: 'why',
    path: '/why',
    title: 'Why this matters',
    section: 'intro',
    track: 'main',
    component: 'why',
    minute: 3,
    hero: {
      kicker: 'Part 1 · Why',
      title: 'Twice a year is not practice',
      subtitle:
        'Most developers get to design a system a handful of times in a career, and every time the stakes are real. Katas turn a rare, expensive event into a repeatable habit.',
      bullets: [
        'Juniors practise without production risk',
        'Seniors coach, and sharpen their own judgement',
        'Everyone learns to read the same picture',
        'Being wrong costs a marker, not a budget',
      ],
      quote: {
        text: 'So how are we supposed to get great architects, if they only get the chance to architect fewer than a half-dozen times in their career?',
        by: 'Ted Neward, Architectural Katas',
      },
    },
    notes: [
      'Read the Neward quote aloud, then pause. Connect it to the hands you counted: for most people the number was below five.',
      'Key claim: architecture is a skill, and skills need repetitions. Production gives you one repetition a year, with real money attached.',
      'Click the persona toggle, junior first. Fear: designing something wrong that costs the company for years. Gain: a safe place to be wrong on paper.',
      'Switch to senior and architect: they coach, hear other views and notice their own blind spots. Then organisation: one design language, faster small decisions.',
      'Show the cost-of-being-wrong comparison. In production you learn you were wrong after months and a budget. In a kata, after forty-five minutes and a marker.',
      'Five minutes here. Do not read every persona; pick two that match the room. Transition: "So what does that shared language look like in practice?"',
    ],
  },
  {
    id: 'shared-language',
    path: '/shared-language',
    title: 'One shared language',
    section: 'intro',
    track: 'main',
    component: 'shared-language',
    minute: 8,
    hero: {
      kicker: 'Part 1 · Why',
      title: 'Everyone can read the same picture',
      subtitle:
        'A small change gets architected in minutes when the team shares one vocabulary for systems, containers and components. Without it, the same change becomes a meeting.',
      bullets: [
        'Same words: person, system, container, component',
        'Same pictures: context, containers, components',
        'Small changes get designed, not just built',
        'Reviews become conversations instead of translations',
      ],
    },
    notes: [
      'Set the scene: a small feature request, say a new export for a report. Two versions of the same conversation, before and after the team learned C4.',
      'Click "before": the words drift. Service, module, backend, "the API". Nobody is sure they mean the same thing, and the decision slips to another meeting.',
      'Click "after": same people, same change, now pointing at a container diagram. Which container owns it, which line changes, done in minutes.',
      'Point at the time-to-decision indicator. The gain is not the diagram itself, it is that everyone reads it the same way.',
      'Key claim: a shared vocabulary is what lets small changes get architected at all. Without it, only big projects get design attention.',
      'Two minutes here. Transition: "The fastest way to build that vocabulary is to practise it together. That is what a kata is for."',
    ],
  },
  {
    id: 'katas',
    path: '/katas',
    title: 'What is a kata',
    section: 'method',
    track: 'main',
    component: 'katas',
    minute: 10,
    hero: {
      kicker: 'Part 2 · The method',
      title: 'A design problem with no right answer',
      subtitle:
        'Architectural Katas were created by Ted Neward: a short case, a small group, a moderator who plays the customer, and a room that asks hard but fair questions. Neal Ford keeps the public list.',
      bullets: [
        'Groups of three to five, mixed experience',
        'The moderator plays the customer, ask them anything',
        'Present, take hard but fair questions, then vote',
        'No right answer, only trade-offs you can defend',
      ],
    },
    notes: [
      'Origin in one line: Ted Neward created Architectural Katas around 2011, Neal Ford maintains the public list, Ford and Mark Richards ran O\'Reilly kata events. Public domain.',
      'The format: groups of three to five, a moderator plays the customer, every group presents, the other groups ask hard but fair questions, the room votes.',
      'Click through the kata anatomy: description, users, requirements, context. Stop on requirements: they are deliberately incomplete. The gaps are where the design happens.',
      'Example: a kata says "thousands of truck drivers a day". Nobody says how many at once. A good group asks; a great group writes the assumption on the diagram.',
      'Show "what a kata is not": no right answer, no laptops for research, any technology as long as you can defend it.',
      'Five minutes here. Transition: "Let me show you the kata that runs through the rest of this talk."',
    ],
  },
  {
    id: 'case',
    path: '/case',
    title: 'The Westhaven kata',
    section: 'method',
    track: 'main',
    component: 'case',
    minute: 15,
    hero: {
      kicker: 'Part 2 · The method',
      title: 'Westhaven: 1.5 million containers, nobody in the yard',
      subtitle:
        'A fictional operator builds an automated container terminal and needs the software that plans, dispatches and controls it: from a stowage plan arriving to a truck leaving the gate with the right box.',
      bullets: [
        'Planning, real-time equipment control, gate, integrations',
        'Three vendors, three PLC protocols, a fourth being negotiated',
        'Around the clock, an hour down costs six figures',
        'No change may put two machines on a collision course',
      ],
    },
    notes: [
      'Read the kata card like a customer: planning and control software for a new automated terminal, 1.5 million containers a year, nobody in the yard.',
      'Facts to land: 24/7, an hour of downtime costs six figures, three vendors with different PLC protocols, safety certification, and the operator wants to sell the software later.',
      'Click "ask the customer": these are the questions groups typically ask. Reveal one or two answers, not all of them. You are modelling the facilitator.',
      'Example: "What happens when the yard network drops?" Answer as the customer: equipment stops safely and resumes; planning can wait, control cannot.',
      'Say it explicitly: the facilitator is the customer. Answer what is asked, invent consistently, never volunteer the design.',
      'Five minutes here. Transition: "Before a group can draw this, it needs a way to draw. That is C4."',
    ],
  },
  {
    id: 'c4',
    path: '/c4',
    title: 'C4 in four minutes',
    section: 'method',
    track: 'main',
    component: 'c4',
    minute: 20,
    hero: {
      kicker: 'Part 2 · The method',
      title: 'Four zoom levels, one map everyone can read',
      subtitle:
        'Simon Brown\'s C4 model: people, software systems, containers, components and code, drawn as system context, container, component and code diagrams. Notation independent, so a marker and sticky notes are enough.',
      bullets: [
        'C1 system context: who uses it, what it talks to',
        'C2 containers: deployable units, with the technology named',
        'C3 components: inside one container, only where it matters',
        'Every diagram: title, legend, labelled one-way lines',
      ],
    },
    notes: [
      'The abstractions: person, software system, container, component, code. The core diagrams zoom in on them: context, container, component, code. Say the levels, do not lecture.',
      'Click C1: Westhaven in context. The people, the platform, the external systems including the equipment PLC fleet. No technology on this level.',
      'Click C2: the same system opened up. Planning web app, TOS core, equipment control, vendor PLC adapters, message broker, stores. Technology on every box.',
      'Click C3 briefly: inside equipment control, the job dispatcher, traffic manager and safety-zone monitor. Say that C3 is optional and only for the containers that matter.',
      'Toggle the notation checklist: title, legend, labelled unidirectional relationships, technology on containers, descriptions on elements. Watch what a sloppy diagram misses light up.',
      'Example: an unlabelled line is a decision nobody made. "Uses" is not a label. "Sends move jobs to" plus the protocol is.',
      'Seven minutes here, the longest method page. Transition: "Put katas and C4 together and you get the session loop."',
    ],
  },
  {
    id: 'session-format',
    path: '/session-format',
    title: 'The session loop',
    section: 'method',
    track: 'main',
    component: 'session-format',
    minute: 27,
    hero: {
      kicker: 'Part 2 · The method',
      title: 'Draw, get feedback, ask, zoom in, repeat',
      subtitle:
        'Groups draw a system context diagram, the other groups give feedback, open questions go to the facilitator, then everyone zooms in to containers and does it again. If there is time, a group splits up for components.',
      bullets: [
        'Round 1: system context in fifteen minutes',
        'Feedback: one like, one challenge, one question',
        'Clarify with the facilitator, then containers',
        'Optional: split the group and draw components',
      ],
    },
    notes: [
      'Step through the phases with the stepper. Name the deliverable of each phase: a diagram, a list of questions, a decision. Never a slide deck.',
      'Timeboxes for ninety minutes: fifteen for C1, eight for feedback, three to clarify, twelve for C2. Click "start timer" on one phase to show it works.',
      'The feedback rules matter more than the drawing rules: hard but fair, one like, one challenge, one question, two minutes per group.',
      'Switch the session length to 60 and 180 minutes: the loop stays the same, only the timeboxes and the number of iterations change.',
      'Facilitator role in one line: you are the customer, the clock and the referee. You never draw.',
      'Example: in feedback, two groups discover they read "gate" differently. That question goes to the facilitator, and the answer goes on both diagrams.',
      'Five minutes here. Transition: "That is the method. Now the thinking you bring into it, starting with three laws."',
    ],
  },
  {
    id: 'laws',
    path: '/laws',
    title: 'Laws of architecture',
    section: 'thinking',
    track: 'main',
    component: 'laws',
    minute: 32,
    hero: {
      kicker: 'Part 3 · Architectural thinking',
      title: 'Every decision is a trade-off, and why beats how',
      subtitle:
        'Three laws from Fundamentals of Software Architecture. They referee every kata discussion: no option is free, the reasoning is the deliverable, and most choices sit somewhere on a spectrum.',
      bullets: [
        'First law: everything in software architecture is a trade-off',
        'Second law: why is more important than how',
        'Third law: most decisions are a spectrum, not binary',
      ],
      quote: {
        text: 'Everything in software architecture is a trade-off.',
        by: 'Richards & Ford, Fundamentals of Software Architecture',
      },
    },
    notes: [
      'Read the first law from the hero. Then: if a group presents an option without a cost, the room has not found the cost yet.',
      'Second law, why is more important than how. The diagram is the how, the reasoning is the why, and feedback should go after the why.',
      'Third law, new in the second edition: most decisions are not binary, they sit on a spectrum between extremes. Point at the sliders.',
      'Drag monolith towards distributed: you gain independent deployment and fault isolation, you lose simplicity, cost and latency. Stop in the middle on purpose.',
      'Drag sync towards async for Westhaven: the control loop wants synchronous, predictable latency, planning can be asynchronous. Same system, two positions.',
      'Shared database to database per service: show that the middle exists. Groups often think they must pick an extreme.',
      'Three minutes here. Transition: "Trade-offs against what? Against the characteristics you chose. Next page."',
    ],
  },
  {
    id: 'characteristics',
    path: '/characteristics',
    title: 'Characteristics',
    section: 'thinking',
    track: 'main',
    component: 'characteristics',
    minute: 35,
    hero: {
      kicker: 'Part 3 · Architectural thinking',
      title: 'Pick at most seven, let three drive',
      subtitle:
        'Architecture characteristics are the qualities a system must have: operational, structural and cross-cutting. Some are explicit in the requirements, most are implicit, and the top three decide the style.',
      bullets: [
        'Operational: performance, availability, scalability, fault tolerance',
        'Structural: modularity, deployability, testability, extensibility',
        'Cross-cutting: security, overall cost, legal, safety',
        'The implicit ones hide in the context section',
      ],
    },
    notes: [
      'Three groups, quickly: operational (performance, availability, fault tolerance), structural (modularity, deployability, testability), cross-cutting (security, cost, legal). Do not read the full lists.',
      'The rule from the book: pick at most seven, and let the top three drive the decision. More than seven means nobody decided.',
      'Explicit versus implicit: "24/7" is explicit availability. "We want to sell it to other terminals" is implicit extensibility. Read the context section twice.',
      'Open the picker and ask the room for a top three for Westhaven. Take two shouts, click them, then reveal the worked choice.',
      'Worked choice: availability, fault tolerance, performance. Extensibility for the vendor plug-ins and testability through the emulator come next. Safety sits across everything as a constraint.',
      'Switch the context to the bootstrapped-startup variant: same requirements, now cost and simplicity lead. Characteristics come from the business, not from the technology.',
      'Three minutes here. Transition: "With a top three in hand, the star ratings give you a shortlist in one minute."',
    ],
  },
  {
    id: 'star-ratings',
    path: '/star-ratings',
    title: 'The star ratings',
    section: 'thinking',
    track: 'main',
    component: 'star-ratings',
    minute: 38,
    hero: {
      kicker: 'Part 3 · Architectural thinking',
      title: 'Stars make a shortlist, context makes the decision',
      subtitle:
        'Fundamentals of Software Architecture rates nine styles on eleven characteristics, one to five stars, plus partitioning type and number of quanta. Sort by your top three and the field narrows fast.',
      bullets: [
        'Nine styles, eleven characteristics, one to five stars',
        'Plus partitioning type and number of quanta',
        'Sort by your driving characteristics, shortlist three or four',
        'There is no best architecture, only the least worst',
      ],
    },
    notes: [
      'Explain the table in one line: every style rated one to five stars on eleven characteristics, plus partitioning type and quanta. Ratings from the book, second edition.',
      'Click fault tolerance to sort: the distributed styles rise, layered sinks. Then click performance and watch the order change. The sorting is the lesson, not the numbers.',
      'Tick event-driven, microservices and service-based, then open the radar compare. The shapes differ more than the totals do. That difference is the conversation.',
      'Say the warning: stars are a shortlist tool. A five-star style your team cannot operate is a one-star decision. Context is king.',
      'Example: for Westhaven sort by fault tolerance, reliability and performance. The shortlist becomes event-driven, microservices, space-based and service-based. We decide on the design page.',
      'Three minutes here. Transition: "To read that table you need to know the nine styles. Six minutes, nine cards."',
    ],
  },
  {
    id: 'styles',
    path: '/styles',
    title: 'Nine styles',
    section: 'styles',
    track: 'main',
    component: 'styles',
    minute: 41,
    hero: {
      kicker: 'Part 4 · Architecture styles',
      title: 'Nine named shapes, so groups can compare them',
      subtitle:
        'Four monolithic styles and five distributed ones, as named in the book. Knowing the names lets a group say "service-based with an event backbone" instead of pointing at boxes.',
      bullets: [
        'Monolithic: layered, modular monolith, pipeline, microkernel',
        'Distributed: service-based, event-driven, space-based, orchestration-driven SOA, microservices',
        'Each has a topology, star ratings and known pitfalls',
        'Press the down arrow for the deep dives',
      ],
    },
    notes: [
      'Do not present all nine. Name the two families, then click three cards: layered, event-driven, microservices. Thirty seconds each.',
      'Layered: the default, technically partitioned, and the sinkhole anti-pattern where layers only pass data through. Every room has built one.',
      'Event-driven: broker topology, asynchronous, strong on performance and fault tolerance, weak on flows you can follow without tooling.',
      'Microservices: many quanta, data ownership per service, and the honest cost: sagas, latency, operational maturity. Popular is not the same as fitting.',
      'Open compare mode with service-based next to microservices: same domain partitioning, very different number of quanta and cost. That is the usual real-world choice.',
      'Point at the deep-dive pages: the down arrow or a card opens one. Topology, ratings against the average, when to use, Westhaven in this style.',
      'Six minutes here, be strict. Transition: "Now let us pick one for Westhaven and show the reasoning."',
    ],
  },
  {
    id: 'case-design',
    path: '/case-design',
    title: 'Westhaven: the design',
    section: 'styles',
    track: 'main',
    component: 'case-design',
    minute: 47,
    hero: {
      kicker: 'Part 4 · Architecture styles',
      title: 'An event backbone, coarse services, plug-in adapters',
      subtitle:
        'The worked design: an event-driven backbone between planning and real-time control, service-based decomposition into coarse domain services, and microkernel plug-ins for the vendor PLC adapters. Two quanta with different availability and latency needs.',
      bullets: [
        'Planning and real-time control are separate quanta',
        'Broker topology between TOS and equipment control',
        'Vendor PLC adapters as plug-ins inside equipment control',
        'Rejected: microservices, layered monolith, space-based',
      ],
    },
    notes: [
      'Walk the tabs in order: shortlist, decision, quanta, ADR. Each tab is one step of the same reasoning. Do not jump to the diagram.',
      'Shortlist tab: the stars gave event-driven, microservices, space-based and service-based. Say in one sentence why each survived the sort.',
      'Decision tab: an event-driven backbone in broker topology between planning (TOS) and control (ECS), coarse service-based domain services, microkernel plug-ins for the vendor PLC adapters.',
      'Quanta tab: two main quanta. Planning and real-time control need different availability and latency, so they get their own quantum. Point at the boundary on the C2.',
      'ADR tab: Nygard template with the rejected alternatives. Microservices: too many quanta and too much latency for a safety-critical control loop. Layered monolith: no fault isolation.',
      'Space-based was rejected on testability; it is not a control-system fit. Then show "what we deliberately did not decide yet". That list is a feature, not a gap.',
      'Key claim: this is one defensible answer, not the answer. A group choosing a modular monolith with a strict control boundary can win the vote if their why is better.',
      'Five minutes here. Transition: "We have a design on paper. Before anyone builds it, let us try to break it on paper too."',
    ],
  },
  {
    id: 'risk-storming',
    path: '/risk-storming',
    title: 'Risk storming',
    section: 'practice',
    track: 'main',
    component: 'risk-storming',
    minute: 52,
    hero: {
      kicker: 'Part 5 · Test it on paper',
      title: 'Break the design before anyone builds it',
      subtitle:
        'Risk storming, by Simon Brown: draw the diagram, write risks individually and in silence, converge on the diagram, review and prioritise. Each risk scores probability times impact: 1 to 2 low, 3 to 4 medium, 6 to 9 high.',
      bullets: [
        'Draw the diagram everyone will point at',
        'Ten minutes of silent, individual risk writing',
        'Converge: every sticky goes on the diagram',
        'Review, prioritise, turn the top risks into work',
      ],
    },
    notes: [
      'Four steps, said once: draw the diagram, ten minutes of silent individual risk writing with probability times impact, converge on the diagram, review and prioritise.',
      'Silence matters, say why: the first loud opinion anchors the room. Writing alone first gets every risk on the wall, including the quiet ones.',
      'Click "seed demo risks" on the Westhaven C2. Broker single point of failure lands as 3 by 3, red. AGV deadlock and yard wireless partition are 2 by 3.',
      'Click an element yourself, say the gate OCR, and add a sticky: probability 3, impact 1, medium. Watch it appear in the register sorted by score.',
      'Ask the room for one risk nobody has written yet. There is always one. Add it live. That is the whole technique.',
      'Point at the side panel: ADRs, what-if scenarios, fitness functions and katas themselves are the siblings. One line each, do not open them.',
      'Press H if the board needs the full screen. Five minutes here, hard stop at minute 57. Transition: "Enough watching. Your turn. Stand up."',
    ],
  },
  {
    id: 'live-setup',
    path: '/live/setup',
    title: 'Form groups',
    section: 'live',
    track: 'main',
    component: 'live-setup',
    minute: 57,
    hero: {
      kicker: 'Live round · Setup',
      title: 'Three to five people, one marker, no laptops',
      subtitle:
        'Mix experience and roles in every group, then pick a scribe and a presenter. You get paper, sticky notes, a C4 legend card, and a customer to question.',
      bullets: [
        'Groups of three to five, mixed experience and roles',
        'One scribe draws, one presenter speaks for the group',
        'A3 sheets or a whiteboard, sticky notes, markers',
        'Laptops closed, the customer answers questions',
      ],
    },
    notes: [
      'Set the participants counter to the head count; the page suggests the number of groups. Say the group numbers out loud and point where each group sits.',
      'Mix on purpose: split colleagues, put a junior with a senior, a tester with a backend developer. The shared language only grows across roles.',
      'Repeat the rules: no laptops, any technology as long as you can defend it, questions for the customer at any time, and you are the customer.',
      'Hand out materials while the counter is on screen: A3 sheets or a whiteboard per group, sticky notes, markers, one C4 legend card each.',
      'Scaling reminder for your own future sessions: one facilitator for up to twenty people, an assistant for every extra ten.',
      'Two minutes, no more. Click "pick a kata" and move to the library.',
    ],
  },
  {
    id: 'library',
    path: '/library',
    title: 'Kata library',
    section: 'live',
    track: 'main',
    component: 'library',
    minute: 59,
    hero: {
      kicker: 'Live round · Pick a kata',
      title: 'Ten classic katas, one of them is yours',
      subtitle:
        'Public domain katas from the list Ted Neward started and Neal Ford maintains, lightly paraphrased and linked to the source. Pick one at random or choose one that fits the room.',
      bullets: [
        'Random pick, or choose one from the list',
        'The pick is remembered on the live pages',
        'Facilitator hints stay hidden behind a toggle',
      ],
    },
    notes: [
      'Click the random picker and let the titles cycle. If it lands on something too heavy for a first round, pick again, openly.',
      'For a mixed room, Hot Diggety Dog is the recommended first kata: small and concrete.',
      'Read the chosen kata aloud from its detail page, big type, once. Users, requirements, context. Do not interpret it yet.',
      'Keep the facilitator hints toggled off while the room can see the screen. They contain the suggested driving characteristics, and finding those is up to the groups.',
      'Say that every kata links to its source in the public list. Groups can reread it on their phones.',
      'One minute here. The pick is remembered on the live pages. Go to Round 1 and start the timer as you arrive.',
    ],
  },
  {
    id: 'live-c1',
    path: '/live/c1',
    title: 'Round 1: context',
    section: 'live',
    track: 'main',
    component: 'live-c1',
    minute: 60,
    timerPreset: 'c1-round',
    hero: {
      kicker: 'Live round · 15 minutes',
      title: 'Draw the system context: who, what, and which lines',
      subtitle:
        'People, the system you are building, the external systems it talks to, and a labelled arrow for every relationship. Title and legend included, questions to the customer at any time.',
      bullets: [
        'Every person and every external system gets a box',
        'Every line gets a label and one direction',
        'Title, legend, and your assumptions on sticky notes',
        'Stuck on a question? Ask the customer',
      ],
    },
    notes: [
      'Start the 15-minute timer the moment you land here. Read the checklist aloud once, then step away from the screen.',
      'Walk between the groups. Answer questions as the customer, consistently. Write down any answer you improvise so every group hears the same story.',
      'Watch for the classic mistakes: a box called "backend", lines without labels, technology on a C1. Ask a question instead of correcting.',
      'Example prompt for a stuck group: "Who is the first person that touches this system on a Monday morning, and what do they need?"',
      'At five minutes left, say so. At two minutes, ask every group to add title and legend now. Unfinished is fine, unlabelled is not.',
      'The timer pill in the footer follows you to other pages, so you can show the kata page again without losing the clock.',
      'Hard stop at minute 75. Move to the feedback round even if a group wants two more minutes. Timeboxes are the format.',
    ],
  },
  {
    id: 'live-feedback',
    path: '/live/feedback',
    title: 'Feedback round',
    section: 'live',
    track: 'main',
    component: 'live-feedback',
    minute: 75,
    timerPreset: 'feedback',
    hero: {
      kicker: 'Live round · 8 minutes',
      title: 'Hard but fair: one like, one challenge, one question',
      subtitle:
        'Each group reviews the next group\'s diagram. Two minutes per group: one thing that works, one decision you would challenge, one question you would ask the customer.',
      bullets: [
        'Group one reviews group two, the last reviews the first',
        'Two minutes each: presenter answers, scribe writes',
        'Go after the reasoning, not the drawing skills',
        'Questions for the customer go on the parking list',
      ],
    },
    notes: [
      'Start the 8-minute timer. Show the rotation on screen: group one walks to group two, and the last group walks to the first.',
      'Read the rules once: one like, one challenge, one question, two minutes per group. Hard but fair means attack the reasoning, never the person.',
      'Use the prompts per C4 level if a group goes quiet. "Which external system would hurt most if it disappeared?" is a good C1 opener.',
      'Any question the presenting group cannot answer goes on the "park it for the facilitator" list. Do not answer it during the rotation.',
      'Listen for the moment two groups discover they drew a different system from the same text. Say it out loud in the debrief.',
      'Clarify round afterwards: use the clarify preset, three minutes on the parked questions. Answer as the customer, the same answer for everyone.',
      'The rotation ends at minute 83. If you are behind, skip Round 2 and go straight to the debrief. C1 plus feedback is a complete session.',
    ],
  },
  {
    id: 'live-c2',
    path: '/live/c2',
    title: 'Round 2: containers',
    section: 'live',
    track: 'main',
    component: 'live-c2',
    minute: 83,
    timerPreset: 'c2-round',
    hero: {
      kicker: 'Live round · 12 minutes · optional',
      title: 'Zoom in: containers, technology, and where quanta live',
      subtitle:
        'Open up the system box: deployable units, a technology on each, protocols on the lines, data stores drawn, and your quanta boundaries marked. If there is time, split the group and draw one C3.',
      bullets: [
        'Every container: a name, a technology, a responsibility',
        'Every line: a label and a protocol',
        'Draw the data stores and say who owns them',
        'Time left? Split up and draw one C3',
      ],
    },
    notes: [
      'Only run this round if the clock allows twelve full minutes plus a debrief. Otherwise skip to the debrief and say why.',
      'Start the 12-minute timer. Read the checklist: technology per container, protocols on the lines, data stores, where the quanta are.',
      'Remind groups to carry the feedback forward: the challenge they received should be visible as a decision on the C2.',
      'Classic questions to ask: why does one database serve everything, what does the line labelled "REST" actually carry, which container has no technology yet?',
      'If a group is fast, split them: two people draw a C3 of the container with the most risk. Choose that container out loud.',
      'The plan has the debrief at minute 83. If you ran this round, take the time from the playbook, not from the debrief.',
    ],
  },
  {
    id: 'live-debrief',
    path: '/live/debrief',
    title: 'Debrief',
    section: 'live',
    track: 'main',
    component: 'live-debrief',
    minute: 83,
    hero: {
      kicker: 'Live round · Debrief',
      title: 'Same kata, different diagrams, none of them wrong',
      subtitle:
        'Look at every diagram once more. What did each group decide, what did they assume, and what changed after feedback? Pin one key trade-off per group.',
      bullets: [
        'What was your hardest decision, and why?',
        'Which question changed your diagram?',
        'What would you draw first next time?',
      ],
      quote: {
        text: 'There are no right answers, only trade-offs you can explain.',
        by: 'The room, five minutes ago',
      },
    },
    notes: [
      'Gallery walk first: every group holds up its diagram for thirty seconds, no commentary yet. Let the room see the variety.',
      'Run the reflection prompts one at a time and ask a different group each time. Hardest decision, the question that changed the diagram, what to draw first next time.',
      'Pin one key trade-off per group on the board: the scribe says it, you type it. One line each. It stays in this browser only.',
      'Name what you heard during the rounds: two groups reading "gate" differently, a box called "backend", an assumption written on a sticky note. Praise the sticky note.',
      'Land the claim: same text, five different systems, none wrong. The reasoning each group can give is the deliverable. That is the second law, live in the room.',
      'Three minutes here. Transition: "You have done one round. Here is how to run the next one at your company."',
    ],
  },
  {
    id: 'playbook',
    path: '/playbook',
    title: 'Run it yourself',
    section: 'wrapup',
    track: 'main',
    component: 'playbook',
    minute: 86,
    hero: {
      kicker: 'Part 6 · Bring it home',
      title: 'Ninety minutes, once a month, no budget needed',
      subtitle:
        'A checklist for running kata rounds at your company: what to prepare, what to do on the day, what to keep afterwards. One facilitator per twenty people, an assistant for every extra ten.',
      bullets: [
        'Before: a kata, a room with wall space, A3 sheets',
        'During: customer, clock and referee, never draw',
        'After: photograph every diagram, keep the parked questions',
        'Variants: lunch C1-only, full day, remote with a whiteboard tool',
      ],
    },
    notes: [
      'Open the accordion section by section: before, during, after. Read only the headings; the room can read the details on their phones.',
      'Before: pick the kata the day before, book a room with wall space, A3 sheets or big whiteboards, sticky notes, markers, groups mixed by role and experience.',
      'During: you are customer, clock and referee. One facilitator for up to twenty people, an assistant for every extra ten. Never draw for a group.',
      'After: photograph every diagram, keep the parked questions, pick the next kata. Ninety minutes once a month is the rhythm that builds the language.',
      'Show the variants: a lunch session with C1 only, a full day with three or four iterations, remote with Excalidraw or Miro.',
      'Click "copy agenda" and say that nobody needs permission or budget to run the first one. A room, paper and five colleagues.',
      'Two minutes here. Transition: "Before the references, a short story about how this started for me."',
    ],
  },
  {
    id: 'story',
    path: '/story',
    title: 'My story',
    section: 'wrapup',
    track: 'main',
    component: 'story',
    minute: 88,
    hero: {
      kicker: 'Part 6 · Bring it home',
      title: '[PLACEHOLDER] My story',
      subtitle:
        '[PLACEHOLDER] How I ended up running katas, what we tried, what happened, what I would do differently.',
      bullets: [
        '[PLACEHOLDER] How it started',
        '[PLACEHOLDER] What we tried',
        '[PLACEHOLDER] What happened',
        '[PLACEHOLDER] What I would do differently',
      ],
    },
    notes: [
      '[PLACEHOLDER] The first time you drew an architecture for real: what went wrong, and how long before you found out?',
      '[PLACEHOLDER] The first kata session you ran: how many people, which kata, what surprised you?',
      '[PLACEHOLDER] What did you try that did not work: session length, group size, tooling, remote?',
      '[PLACEHOLDER] One moment where a junior changed the mind of a senior, on paper.',
      '[PLACEHOLDER] What changed in daily work after a few months: reviews, small changes, vocabulary?',
      '[PLACEHOLDER] What you would do differently next time, in one sentence.',
      'One minute here, two at most. Transition: "Everything I used today is on the next page."',
    ],
  },
  {
    id: 'references',
    path: '/references',
    title: 'References',
    section: 'wrapup',
    track: 'main',
    component: 'references',
    minute: 89,
    hero: {
      kicker: 'Part 6 · Bring it home',
      title: 'Everything in this talk, with a link',
      subtitle:
        'Books, sites, tools and videos, filterable by type and topic. The deck is online, so every link opens from your phone.',
      bullets: [
        'Fundamentals of Software Architecture, 2nd edition, Richards & Ford',
        'c4model.com, riskstorming.com, nealford.com/katas',
        'Tools: Structurizr, IcePanel, Excalidraw, draw.io, Mermaid C4',
      ],
    },
    notes: [
      'Do not read the list. Filter by "katas" and point at the Neal Ford kata list and the Software Architecture Monday lesson on running a kata session.',
      'Filter by "c4" and show the notation checklist on c4model.com; it is the same checklist as on the C4 page.',
      'Say that every star rating in this deck comes from Fundamentals of Software Architecture, second edition, and that the book holds the full tables.',
      'Mention the tools once: Structurizr or IcePanel if you want a model behind the diagrams, Excalidraw or Miro for remote rounds.',
      'Thirty seconds here. Transition: "Three things to take home."',
    ],
  },
  {
    id: 'closing',
    path: '/closing',
    title: 'Thank you',
    section: 'wrapup',
    track: 'main',
    component: 'closing',
    minute: 89,
    hero: {
      kicker: 'JEM-id Dev Cafe 2026 · Randy Vroegop',
      title: 'Practise architecture together, on paper, next week',
      subtitle:
        'Thank you. The deck, the kata library and a sixty-minute agenda for your first round are behind the QR code.',
      bullets: [
        'Architecture is a skill, and skills need repetitions',
        'C4 gives the whole team one design language',
        'Test it on paper before you commit',
      ],
    },
    notes: [
      'Read the three takeaways from the hero, one breath each. Then stop talking and leave the QR code on screen.',
      'Point at "your first kata next week": a pre-filled sixty-minute agenda. Ask for hands: who will run one before the next Dev Cafe?',
      '[PLACEHOLDER] your contact details are in src/content/site.ts',
      'Take questions here with the QR code still visible. For a question about one style, jump to its deep-dive page through the ToC.',
      'Minute 89 to 90. If you are over time, skip questions and say where people can find you afterwards. Thank whoever brought the paper and markers.',
    ],
  },
]
