import type { Reference } from './types'

/**
 * Further reading, sites and tools shown on the references page. Ordered by
 * type: books, sites and videos, tools, articles.
 */
export const references: Reference[] = [
  /* ---------------------------------------------------------------- books */
  {
    id: 'fundamentals-2e',
    type: 'book',
    title: 'Fundamentals of Software Architecture (2nd edition)',
    by: 'Mark Richards, Neal Ford',
    url: 'https://www.oreilly.com/library/view/fundamentals-of-software/9781098175504/',
    topics: ['characteristics', 'styles', 'katas'],
    note: 'Source of the star ratings in this deck, plus the definitive chapters on characteristics, styles and katas',
  },
  {
    id: 'hard-parts',
    type: 'book',
    title: 'Software Architecture: The Hard Parts',
    by: 'Neal Ford, Mark Richards, Pramod Sadalage, Zhamak Dehghani',
    url: 'https://www.oreilly.com/library/view/software-architecture-the/9781492086888/',
    topics: ['styles', 'techniques', 'katas'],
    note: 'Trade-off analysis for distributed architectures, told through the Sysop Squad kata from start to finish',
  },
  {
    id: 'head-first-architecture',
    type: 'book',
    title: 'Head First Software Architecture',
    by: 'Raju Gandhi, Mark Richards, Neal Ford',
    url: 'https://www.oreilly.com/library/view/head-first-software/9781098134341/',
    topics: ['characteristics', 'styles', 'katas'],
    note: 'The visual, exercise-driven introduction, ideal for developers new to architectural thinking',
  },
  {
    id: 'evolutionary-architectures-2e',
    type: 'book',
    title: 'Building Evolutionary Architectures (2nd edition)',
    by: 'Neal Ford, Rebecca Parsons, Patrick Kua, Pramod Sadalage',
    url: 'https://www.oreilly.com/library/view/building-evolutionary-architectures/9781492097532/',
    topics: ['techniques', 'characteristics'],
    note: 'Fitness functions: how to make a characteristic measurable and keep it that way as the system changes',
  },
  {
    id: 'software-architecture-for-developers',
    type: 'book',
    title: 'Software Architecture for Developers',
    by: 'Simon Brown',
    url: 'https://leanpub.com/software-architecture-for-developers',
    topics: ['c4', 'techniques'],
    note: 'Two volumes from the creator of C4, the second one is the book on visualising and documenting architecture',
  },
  {
    id: 'design-it',
    type: 'book',
    title: 'Design It!',
    by: 'Michael Keeling',
    url: 'https://pragprog.com/titles/mkdsa/design-it/',
    topics: ['techniques', 'facilitation'],
    note: 'Design thinking for architects, with a large catalogue of workshop activities to run with a team',
  },
  {
    id: 'just-enough-software-architecture',
    type: 'book',
    title: 'Just Enough Software Architecture',
    by: 'George Fairbanks',
    url: 'https://www.georgefairbanks.com/book/',
    topics: ['techniques'],
    note: 'Risk-driven architecture: do only as much design as the risks justify, the idea behind risk storming',
  },
  {
    id: 'software-architect-elevator',
    type: 'book',
    title: 'The Software Architect Elevator',
    by: 'Gregor Hohpe',
    url: 'https://architectelevator.com/book/',
    topics: ['techniques'],
    note: 'Riding between the penthouse and the engine room, on explaining architecture to the business',
  },

  /* ------------------------------------------------------- sites & videos */
  {
    id: 'c4model',
    type: 'site',
    title: 'The C4 model for visualising software architecture',
    by: 'Simon Brown',
    url: 'https://c4model.com',
    topics: ['c4'],
    note: 'The official reference: the abstractions, the four levels, notation and a frequently asked questions page',
  },
  {
    id: 'c4-notation-checklist',
    type: 'site',
    title: 'C4 notation and diagram checklist',
    by: 'Simon Brown',
    url: 'https://c4model.com/diagrams/notation',
    topics: ['c4'],
    note: 'Print it for the feedback round: every element needs a name, a type, a technology and a description',
  },
  {
    id: 'riskstorming',
    type: 'site',
    title: 'Risk Storming',
    by: 'Simon Brown',
    url: 'https://riskstorming.com',
    topics: ['techniques', 'c4', 'facilitation'],
    note: 'A collaborative technique for finding risks on a C4 diagram, the natural step after the design round',
  },
  {
    id: 'nealford-katas',
    type: 'site',
    title: 'Architectural Katas: the list',
    by: 'Neal Ford',
    url: 'https://nealford.com/katas/list.html',
    topics: ['katas'],
    note: 'The list this session draws from, with the rules of the game on the same page',
  },
  {
    id: 'architecturalkatas',
    type: 'site',
    title: 'Architectural Katas',
    by: 'Ted Neward',
    url: 'https://www.architecturalkatas.com',
    topics: ['katas', 'facilitation'],
    note: 'The original site by the inventor of the format: the rules, the kata list and how to lead a session',
  },
  {
    id: 'fosa-katas',
    type: 'site',
    title: 'Fundamentals of Software Architecture: katas',
    by: 'Mark Richards, Neal Ford',
    url: 'https://fundamentalsofsoftwarearchitecture.com/katas/',
    topics: ['katas', 'facilitation'],
    note: 'The book site explains the format in detail: team rules, discussion, peer review and voting',
  },
  {
    id: 'software-architecture-monday',
    type: 'site',
    title: 'Software Architecture Monday',
    by: 'Mark Richards',
    url: 'https://developertoarchitect.com/lessons/',
    topics: ['styles', 'characteristics', 'techniques'],
    note: 'Free short video lessons, one architecture topic per week, a good source for the styles gallery',
  },
  {
    id: 'sam-lesson-184',
    type: 'video',
    title: 'Lesson 184: Running an Architecture Kata Session',
    by: 'Mark Richards',
    url: 'https://developertoarchitect.com/lessons/lesson184.html',
    topics: ['katas', 'facilitation'],
    note: 'What a kata is, why it is valuable, and the five activities of running your own session',
  },
  {
    id: 'sam-worksheets',
    type: 'site',
    title: 'Architecture characteristics and styles worksheets',
    by: 'Mark Richards',
    url: 'https://developertoarchitect.com/downloads/worksheets.html',
    topics: ['characteristics', 'styles', 'facilitation'],
    note: 'Printable worksheets (PDF, Keynote, PowerPoint) for picking characteristics and comparing styles at the table',
  },
  {
    id: 'adr-github',
    type: 'site',
    title: 'Architectural Decision Records',
    url: 'https://adr.github.io',
    topics: ['techniques'],
    note: 'Templates, tools and examples for recording decisions as lightweight ADRs next to the code',
  },

  /* ---------------------------------------------------------------- tools */
  {
    id: 'structurizr',
    type: 'tool',
    title: 'Structurizr',
    by: 'Simon Brown',
    url: 'https://structurizr.com',
    topics: ['c4'],
    note: 'Diagrams as code for the C4 model: one model, many views, built by the author of C4',
  },
  {
    id: 'icepanel',
    type: 'tool',
    title: 'IcePanel',
    url: 'https://icepanel.io',
    topics: ['c4'],
    note: 'Collaborative C4 modelling tool with zoomable levels, for teams that prefer a canvas over code',
  },
  {
    id: 'excalidraw',
    type: 'tool',
    title: 'Excalidraw',
    url: 'https://excalidraw.com',
    topics: ['c4', 'facilitation'],
    note: 'Hand-drawn style whiteboard, the closest thing to paper for a remote kata round',
  },
  {
    id: 'drawio-c4',
    type: 'tool',
    title: 'draw.io C4 shape library',
    url: 'https://www.drawio.com/docs/diagram-types/c4-modelling/',
    topics: ['c4'],
    note: 'The built-in C4 shapes in draw.io, with a short guide on modelling each level',
  },
  {
    id: 'mermaid-c4',
    type: 'tool',
    title: 'Mermaid C4 diagrams',
    url: 'https://mermaid.js.org/syntax/c4.html',
    topics: ['c4'],
    note: 'Text-based C4 diagrams that render in Markdown on GitHub and most wikis, still marked experimental',
  },
  {
    id: 'c4-plantuml',
    type: 'tool',
    title: 'C4-PlantUML',
    url: 'https://github.com/plantuml-stdlib/C4-PlantUML',
    topics: ['c4'],
    note: 'PlantUML macros for C4 diagrams, the classic diagrams-as-code option with a large user base',
  },

  /* ------------------------------------------------------------- articles */
  {
    id: 'nygard-adr',
    type: 'article',
    title: 'Documenting Architecture Decisions',
    by: 'Michael Nygard',
    url: 'https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions',
    topics: ['techniques'],
    note: 'The 2011 post that started ADRs: title, context, decision, status and consequences',
  },
  {
    id: 'boucke-organizing-katas',
    type: 'article',
    title: 'Organizing Architectural Katas',
    by: 'Nelis Boucke',
    url: 'https://nelis.boucke.be/post/architectural-katas/',
    topics: ['katas', 'facilitation'],
    note: 'Lessons from two years of running katas: one facilitator per twenty people, strict timeboxes, lots of wall space',
  },
]
